-include ../config.mk

MAN_PAGES_3 := $(wildcard *.3)

INSTALL ?= install
LINK ?= ln -sf

install: install-man3 install-man3-symlinks

install-man3:
	$(INSTALL) -d $(DESTDIR)$(MANDIR)/man3
	$(INSTALL) -m 644 $(MAN_PAGES_3) $(DESTDIR)$(MANDIR)/man3

install-man3-symlinks: install-man3
	$(LINK) abs.3 $(DESTDIR)$(MANDIR)/man3/labs.3
	$(LINK) abs.3 $(DESTDIR)$(MANDIR)/man3/llabs.3
	$(LINK) strchr.3 $(DESTDIR)$(MANDIR)/man3/strchrnul.3
	$(LINK) strtok.3 $(DESTDIR)$(MANDIR)/man3/strtok_r.3
	$(LINK) strlen.3 $(DESTDIR)$(MANDIR)/man3/strnlen.3
	$(LINK) strcmp.3 $(DESTDIR)$(MANDIR)/man3/strncmp.3
	$(LINK) strlcpy.3 $(DESTDIR)$(MANDIR)/man3/strlcat.3
	$(LINK) strstr.3 $(DESTDIR)$(MANDIR)/man3/strnstr.3
	$(LINK) strcat.3 $(DESTDIR)$(MANDIR)/man3/strncat.3
	$(LINK) strcasecmp.3 $(DESTDIR)$(MANDIR)/man3/strncasecmp.3
	$(LINK) strstr.3 $(DESTDIR)$(MANDIR)/man3/strcasestr.3
	$(LINK) memchr.3 $(DESTDIR)$(MANDIR)/man3/memrchr.3
	$(LINK) memcpy.3 $(DESTDIR)$(MANDIR)/man3/mempcpy.3
	$(LINK) strcpy.3 $(DESTDIR)$(MANDIR)/man3/stpcpy.3
	$(LINK) strncpy.3 $(DESTDIR)$(MANDIR)/man3/stpncpy.3
	$(LINK) gethostname.3 $(DESTDIR)$(MANDIR)/man3/sethostname.3
	$(LINK) getdomainname.3 $(DESTDIR)$(MANDIR)/man3/setdomainname.3
	$(LINK) getprogname.3 $(DESTDIR)$(MANDIR)/man3/setprogname.3
	$(LINK) gethostid.3 $(DESTDIR)$(MANDIR)/man3/sethostid.3
	$(LINK) qsort.3 $(DESTDIR)$(MANDIR)/man3/qsort_r.3
	$(LINK) qsort.3 $(DESTDIR)$(MANDIR)/man3/heapsort.3
	$(LINK) qsort.3 $(DESTDIR)$(MANDIR)/man3/heapsort_r.3
	$(LINK) qsort.3 $(DESTDIR)$(MANDIR)/man3/mergesort.3
	$(LINK) qsort.3 $(DESTDIR)$(MANDIR)/man3/mergesort_r.3
	$(LINK) strdup.3 $(DESTDIR)$(MANDIR)/man3/strndup.3
	$(LINK) md4.3 $(DESTDIR)$(MANDIR)/man3/MD4Init.3
	$(LINK) md4.3 $(DESTDIR)$(MANDIR)/man3/MD4Update.3
	$(LINK) md4.3 $(DESTDIR)$(MANDIR)/man3/MD4Final.3
	$(LINK) md4.3 $(DESTDIR)$(MANDIR)/man3/MD4End.3
	$(LINK) md4.3 $(DESTDIR)$(MANDIR)/man3/MD4File.3
	$(LINK) md4.3 $(DESTDIR)$(MANDIR)/man3/MD4Data.3
	$(LINK) md5.3 $(DESTDIR)$(MANDIR)/man3/MD5Init.3
	$(LINK) md5.3 $(DESTDIR)$(MANDIR)/man3/MD5Update.3
	$(LINK) md5.3 $(DESTDIR)$(MANDIR)/man3/MD5Final.3
	$(LINK) md5.3 $(DESTDIR)$(MANDIR)/man3/MD5End.3
	$(LINK) md5.3 $(DESTDIR)$(MANDIR)/man3/MD5File.3
	$(LINK) md5.3 $(DESTDIR)$(MANDIR)/man3/MD5Data.3
	$(LINK) div.3 $(DESTDIR)$(MANDIR)/man3/ldiv.3
	$(LINK) div.3 $(DESTDIR)$(MANDIR)/man3/lldiv.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/verr.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/errx.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/verrx.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/errc.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/verrc.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/warn.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/vwarn.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/warnx.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/vwarnx.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/warnc.3
	$(LINK) err.3 $(DESTDIR)$(MANDIR)/man3/vwarnc.3
