.PATH: ${.CURDIR}/compat

SRCS+=compat_alphasort.c compat_getpwent.c compat_random.c compat_timezone.c creat.c getdtablesize.c getwd.c issetugid.c \
      revoke.c setpgrp.c setruid.c compat_devname.c compat_putenv.c compat_syslog.c compat_unsetenv.c fchroot.c gethostid.c \
      killpg.c sethostid.c setrgid.c sigcompat.c

