.PATH: ${.CURDIR}/gdtoa

SRCS+=dmisc.c dtoa.c gdtoa.c gdtoa_locks.c gethex.c gmisc.c hd_init.c \
      hdtoa.c hexnan.c ldtoa.c misc.c smisc.c strtod.c strtodg.c strtof.c \
      strtold_px.c strtopx.c strtord.c sum.c ulp.c

