.PATH: ${.CURDIR}/stdlib

SRCS+=_env.c _rand48.c a64l.c abort.c aligned_alloc.c atexit.c atof.c atoi.c \
      atol.c atoll.c bsearch.c cxa_thread_atexit.c drand48.c erand48_ieee754.c \
      exit.c getbsize.c getenv.c getopt_long.c getsubopt.c hcreate.c heapsort.c \
      imaxabs.c imaxdiv.c insque.c jemalloc.c jrand48.c l64a.c lcong48.c lldiv.c \
      lrand48.c lsearch.c merge.c mi_vector_hash.c mrand48.c nrand48.c posix_openpt.c \
      pty.c putenv.c qabs.c qdiv.c qsort.c quick_exit.c radixsort.c rand.c rand_r.c \
      random.c reallocarr.c reallocarray.c remque.c seed48.c setenv.c srand48.c \
      strfmon.c strsuftoll.c strtoi.c strtoimax.c strtol.c strtoll.c strtonum.c \
      strtoq.c strtou.c strtoul.c strtoull.c strtoumax.c strtouq.c system.c tdelete.c \
      tfind.c tsearch.c twalk.c unsetenv.c

