.PATH: ${.CURDIR}/stdio

SRCS+=clrerr.c dprintf.c fclose.c fdopen.c feof.c ferror.c fflush.c fgetc.c \
      fgetln.c fgetpos.c fgets.c fgetstr.c fgetwc.c fgetwln.c fgetws.c fileno.c \
      findfp.c flags.c flockfile.c fmemopen.c fopen.c fparseln.c fprintf.c fpurge.c \
      fputc.c fputs.c fputwc.c fputws.c fread.c freopen.c fscanf.c fseek.c fseeko.c \
      fsetpos.c ftell.c ftello.c funopen.c fvwrite.c fwalk.c fwide.c fwprintf.c \
      fwrite.c fwscanf.c getc.c getchar.c getdelim.c getline.c gets.c gettemp.c \
      getw.c getwc.c getwchar.c makebuf.c mkdtemp.c mkostemp.c mkostemps.c mkstemp.c \
      mkstemps.c mktemp.c open_memstream.c open_wmemstream.c perror.c printf.c putc.c \
      putchar.c puts.c putw.c putwc.c putwchar.c refill.c remove.c rewind.c rget.c \
      scanf.c setbuf.c setbuffer.c setvbuf.c snprintf_ss.c sscanf.c stdio.c swprintf.c \
      swscanf.c tempnam.c tmpfile.c tmpnam.c ungetc.c ungetwc.c vasprintf.c vdprintf.c \
      vfprintf.c vfscanf.c vfwprintf.c vfwscanf.c vprintf.c vscanf.c vsnprintf.c \
      vsnprintf_ss.c vsprintf.c vsscanf.c vswprintf.c vswscanf.c vwprintf.c vwscanf.c \
      wbuf.c wprintf.c wscanf.c wsetup.c

