.PATH: ${.CURDIR}/db

SRCS+=bt_close.c bt_delete.c bt_open.c bt_put.c bt_seq.c db.c hash_buf.c hash_func.c hash_page.c ndbmdatum.c rec_delete.c rec_search.c \
      bt_conv.c bt_overflow.c bt_split.c dbfile.c hash.c mpool.c rec_get.c rec_open.c rec_seq.c bt_debug.c bt_get.c bt_page.c bt_search.c \
      bt_utils.c hash_bigkey.c hash_log2.c ndbm.c rec_close.c rec_put.c rec_utils.c
