.PATH: ${.CURDIR}/string

SRCS+=__strsignal.c bcmp.c bm.c consttime_memequal.c explicit_memset.c ffsl.c ffsll.c \
      memccpy.c memcmp.c memmem.c mempcpy.c memrchr.c popcount32.c popcount64.c stpcpy.c \
      stpncpy.c strcasecmp.c strcasestr.c strchrnul.c strcoll.c strcspn.c strdup.c \
      strerror.c strerror_r.c strerror_ss.c stresep.c strlcat.c strlcpy.c strmode.c \
      strncasecmp.c strncat.c strncpy.c strndup.c strnlen.c strnstr.c strpbrk.c strsep.c \
      strsignal.c strspn.c strstr.c strtok.c strtok_r.c strxfrm.c wcscasecmp.c wcscat.c \
      wcschr.c wcscmp.c wcscpy.c wcscspn.c wcsdup.c wcslcat.c wcslcpy.c wcslen.c wcsncasecmp.c \
      wcsncat.c wcsncmp.c wcsncpy.c wcsnlen.c wcspbrk.c wcsrchr.c wcsspn.c wcsstr.c wcstok.c \
      wcswcs.c wmemchr.c wmemcmp.c wmemcpy.c wmemmove.c wmempcpy.c wmemset.c

