.PATH: ${.CURDIR}/termios

SRCS+=cfgetispeed.c cfgetospeed.c cfmakeraw.c cfsetispeed.c cfsetospeed.c cfsetspeed.c tcdrain.c \
      tcflow.c tcflush.c tcgetattr.c tcgetpgrp.c tcgetsid.c tcgetwinsize.c tcsendbreak.c tcsetattr.c \
      tcsetpgrp.c tcsetwinsize.c

