STRING := $(wildcard string/*.c)
CTYPE := $(wildcard ctype/*.c)
LINUX := $(wildcard linux/*.c)
GEN := $(wildcard gen/*.c)
STDLIB := $(wildcard stdlib/*.c)
MD := $(wildcard md/*.c)
LIB := $(wildcard crt/libc_start.c)
COMPAT := $(wildcard compat/OpenBSD/*.c) $(wildcard compat/NetBSD/*.c)
PRINTF := $(wildcard mini-printf/*.c)
ARCH_S := $(wildcard arch/$(MACHINE)/src/gen/*.S)

GENERAL_INCLUDES := $(wildcard include/*.h)
SYSTEM_INCLUDES := $(wildcard include/sys/*.h)
MACHINE_INCLUDES := $(wildcard arch/$(MACHINE)/machine/*.h)

ALL_C_SRCS := $(STRING) $(CTYPE) $(LINUX) $(GEN) $(STDLIB) $(MD) $(LIB) $(COMPAT) $(PRINTF)
ALL_S_SRCS := $(ARCH_S)
C_OBJS := $(ALL_C_SRCS:%.c=%.o)
S_OBJS := $(ALL_S_SRCS:%.S=%.o)
ALL_OBJS := $(C_OBJS) $(S_OBJS)
