.PATH: ${.CURDIR}/citrus/modules

SRCS+=citrus_big5.c citrus_dechanyu.c citrus_euc.c citrus_euctw.c citrus_gbk2k.c citrus_hz.c \
      citrus_iconv_none.c citrus_iconv_std.c citrus_iso2022.c citrus_johab.c citrus_mapper_646.c \
      citrus_mapper_none.c citrus_mapper_serial.c citrus_mapper_std.c citrus_mapper_zone.c \
      citrus_mskanji.c citrus_ues.c citrus_utf1632.c citrus_utf7.c citrus_utf8.c citrus_viqr.c \
      citrus_zw.c

